import { useState } from 'react';

export default function WorkflowDemo({kind,lang}:{kind:'receipt'|'vote';lang:'en'|'id'}) {
  const id=lang==='id';
  const [merchant,setMerchant]=useState('Studio Supply'),[amount,setAmount]=useState('150000'),[category,setCategory]=useState('Supplies');
  const [journal,setJournal]=useState<{merchant:string;amount:number;category:string}|null>(null),[error,setError]=useState('');
  const [phase,setPhase]=useState<'idle'|'open'|'locked'|'results'>('idle'),[choice,setChoice]=useState<number|null>(null),[flow,setFlow]=useState(0);
  const reset=()=>{setMerchant('Studio Supply');setAmount('150000');setCategory('Supplies');setJournal(null);setError('');};
  const choices=id?['Perbaiki koneksi','Jeda ronde','Lanjutkan voting']:['Restore connection','Pause the round','Continue voting'];
  const money=(n:number)=>new Intl.NumberFormat(id?'id-ID':'en-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
  return <section className="workflow" aria-label={kind==='receipt'?'Akun.AI demo':'WGG demo'}>
    <div className="workflow-heading"><span className="eyebrow">{id?'Coba alurnya':'Try the workflow'} / {kind==='receipt'?'Akun.AI':'WGG'}</span><h3>{kind==='receipt'?(id?'Dari struk ke jurnal.':'From receipt to journal.'):(id?'Satu ronde. Tiga pilihan.':'One round. Three choices.')}</h3><p>{kind==='receipt'?(id?'Contoh sintetis. Tidak menjalankan OCR, mengirim data, atau menyimpan apa pun.':'Synthetic example. No OCR runs, no data is sent, and nothing is saved.'):(id?'Simulasi lokal dengan suara fiktif. Bukan koneksi multiplayer.':'A local simulation with fictional votes. Not a multiplayer connection.')}</p></div>
    {kind==='receipt'?<div className="demo-grid"><form onSubmit={e=>{e.preventDefault();const value=Number(amount);if(!merchant.trim()||merchant.trim().length>80||!Number.isFinite(value)||value<=0||value>1000000000||!/^\d+(\.\d{1,2})?$/.test(amount)){setError(id?'Isi merchant dan jumlah positif hingga Rp1 miliar (maks. 2 desimal).':'Enter a merchant and a positive amount up to Rp1 billion (max. 2 decimals).');setJournal(null);return;}setError('');setJournal({merchant:merchant.trim(),amount:value,category});}}>
      <span className="eyebrow">SAMPLE RECEIPT · 001</span><label>{id?'Merchant':'Merchant'}<input value={merchant} maxLength={80} onChange={e=>setMerchant(e.target.value)} required/></label>
      <label>{id?'Jumlah (IDR)':'Amount (IDR)'}<input type="number" min="0.01" max="1000000000" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} required/></label>
      <label>{id?'Kategori':'Category'}<select value={category} onChange={e=>setCategory(e.target.value)}><option value="Supplies">{id?'Perlengkapan':'Supplies'}</option><option value="Transport">{id?'Transportasi':'Transport'}</option><option value="Meals">{id?'Konsumsi':'Meals'}</option></select></label>
      <div className="actions"><button className="primary" type="submit">{id?'Pratinjau jurnal':'Preview journal'} ↗</button><button type="button" onClick={reset}>{id?'Ulangi':'Reset'}</button></div><p role="alert">{error}</p>
    </form><div className="journal" aria-live="polite"><span className="eyebrow">{id?'Pratinjau · bukan pembukuan tersimpan':'Preview · not a saved ledger'}</span><h4>{journal?journal.merchant:(id?'Periksa keseimbangannya.':'Check the balance.')}</h4>{journal?<><table><thead><tr><th>{id?'Akun':'Account'}</th><th>Debit</th><th>{id?'Kredit':'Credit'}</th></tr></thead><tbody><tr><td>{journal.category}</td><td>{money(journal.amount)}</td><td>—</td></tr><tr><td>{id?'Kas':'Cash'}</td><td>—</td><td>{money(journal.amount)}</td></tr></tbody></table><p>{id?'Seimbang: debit = kredit. Contoh pembelian tunai sederhana; pajak tidak dimodelkan.':'Balanced: debit = credit. A simple cash purchase example; tax is not modeled.'}</p></>:<p>{id?'Ubah struk lalu pilih Pratinjau jurnal. Dua sisi transaksi akan muncul di sini.':'Edit the receipt, then choose Preview journal. Both sides of the transaction appear here.'}</p>}</div></div>
    :<div className="demo-grid"><div><p>{id?'Skenario: koneksi peserta terputus di tengah acara. Apa langkah operator?':'Scenario: a participant loses connection during the event. What should the operator do?'}</p><p className="eyebrow" aria-live="polite">{({idle:id?'Siap':'Ready',open:id?'Pilihan dibuka':'Choices open',locked:id?'Pilihan terkunci':'Choice locked',results:id?'Hasil ilustratif':'Illustrative results'})[phase]}</p>
      {phase==='idle'?<button className="primary" onClick={()=>setPhase('open')}>{id?'Mulai ronde':'Start round'} →</button>:<><div className="vote-choices">{choices.map((label,i)=><button key={label} disabled={phase!=='open'} aria-pressed={choice===i} onClick={()=>{setChoice(i);setPhase('locked');}}>{String.fromCharCode(65+i)} · {label}</button>)}</div>{phase==='locked'&&<button className="primary" onClick={()=>setPhase('results')}>{id?'Lihat hasil simulasi':'Inspect simulated results'} →</button>}{phase==='results'&&<div aria-live="polite">{choices.map((label,i)=><div className="vote-result" key={label}><span>{label} · {[24,61,15][i]}%</span><meter min="0" max="100" value={[24,61,15][i]}/></div>)}<p>{id?'100 suara fiktif tetap; pilihan Anda tidak mengubah data contoh.':'100 fixed fictional votes; your choice does not change the sample data.'}</p></div>}<button className="text-button" onClick={()=>{setPhase('idle');setChoice(null);}}>{id?'Mainkan lagi':'Replay'} ↻</button></>}
    </div><div className="flow-panel"><div className="segmented">{[id?'Peserta':'Participant',id?'Operator':'Operator'].map((label,i)=><button key={i} aria-pressed={flow===i} onClick={()=>setFlow(i)}>{label}</button>)}</div><ol className="flow-diagram">{(flow===0?(id?['Masuk ke ronde','Pilih jawaban','Pilihan terkunci','Lihat hasil']:['Join round','Choose answer','Choice locks','View results']):(id?['Siapkan skenario','Buka pilihan','Kunci ronde','Tampilkan hasil']:['Prepare scenario','Open choices','Lock round','Reveal results'])).map(label=><li key={label}>{label}</li>)}</ol></div></div>}
    <noscript><p>{id?'Demo membutuhkan JavaScript. Studi kasus tetap tersedia melalui tautan di atas.':'The demo requires JavaScript. The complete case study remains available above.'}</p></noscript>
  </section>;
}
